basis: &DEFAULT
  logdir: './tf_logs/'
cbasis: &CDEFAULT
  logdir: '/scratch/users/rmth/tf_logs/'
simulated:
  <<: *DEFAULT
  data_folder: '/home/rasmus/Desktop/shhs_subset/simulated_data/'
n2rem:
  <<: *DEFAULT
  data_folder: '/home/rasmus/Desktop/SSC/processed_data/'
shhs:
  <<: *DEFAULT
  data_folder: '/home/rasmus/Desktop/shhs_subset/processed_data/'
shhs-multimodal:
  <<: *DEFAULT
  data_folder: '/home/rasmus/Desktop/shhs_subset/processed_data_multimodal/'
c-shhs:
  <<: *CDEFAULT
  data_folder: '/scratch/users/rmth/processed_shhs_data/'
c-shhs-multimodal:
  <<: *CDEFAULT
  data_folder: '/scratch/users/rmth/processed_shhs_data_multimodal/'
