local: &DEFAULT
  save_checkpoint_steps: 50
  save_summary_steps: 50
  buffer_size: 1
  train_steps:
  eval_steps: 10
  verbose_shapes: True
  training_hook_n_iter: 25
  throttle_secs: 20
  train_pct: 0.75
  val_pct: 0.5
  batch_size: {'train': 8, 'val': 2, 'test': 2}
cluster:
  <<: *DEFAULT
  save_checkpoint_steps: 100
  save_summary_steps: 100
  train_steps:
  eval_steps: 200 
  throttle_secs: 360
  buffer_size: 50
  batch_size: {'train': 8, 'val': 8, 'test': 8}
